### ISSUE TITLE
aks up - open in browser option

### ISSUE THREAD

**Issue by atbagga** [atbagga/cli-extension-aks-up#16]

**Comment by ishitam8** [comment]
Had a discussion with George on this. 
Opening in the browser switch made less sense in this case because aks up is a long running command and has many intermediate steps involved with an interactive flow.
It only made sense when user is running the command with --do-not-wait switch where we can open the check-run URL in a browser.
@geverghe , Are we planning to add an open switch ?

**Comment by atbagga** [comment]
I just opened it from what I remembered. Feel free to close in case the discussion has already happened.

**Comment by ishitam8** [comment]
Issue is tracked [here](https://github.com/Azure/deploy-to-azure-cli-extension/issues/2)
